#!/usr/bin/env bash
# print domains and subdomains

print_domain_subdomain () {
    domain=$1
    subdomain=$2
    record_type=$(dig +short "$subdomain.$domain" | awk '{if ($0 ~ /^[0-9]/) print "A"; else if ($0 ~ /^([a-fA-F0-9:]+)$/) print "AAAA"; else if ($0 ~ /(\.|\d{1,3}\.)/) print "CNAME"; else print $4}')
    destination=$(dig +short "$subdomain.$domain" | head -n 1)
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$1" "$2"
else
    print_domain_subdomain "$1" "www"
    print_domain_subdomain "$1" "lb-01"
    print_domain_subdomain "$1" "web-01"
    print_domain_subdomain "$1" "web-02"
fi
