#!/usr/bin/env bash
# This script checks DNS records for specified subdomains and displays their details.

function check_subdomain {
    local domain=$1
    local subdomain=$2
    record_type=$(dig +short "$subdomain.$domain" | awk '{print $1}')
    destination=$(dig +short "$subdomain.$domain")
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if at least one argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain=$1
if [ $# -eq 2 ]; then
    subdomain=$2
    check_subdomain "$domain" "$subdomain"
else
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        check_subdomain "$domain" "$sub"
    done
fi
